Up 26
pk-tigers/upwork pull request #15
Opened 2023-04-27 14:34 UTC by majchpa

Added new styles for primary button, secondary button and input, created new components: popup and dropdown-select

2023-04-27 19:29 UTC, aleksanderkus00 commented on frontend/upwork-client/src/app/components/popup/popup.component.css
> +.upwork-btn-primary{
Ta klasa juz jest w `style.scss`

2023-04-27 19:38 UTC, aleksanderkus00 commented
Jest konflik z branchem dev. Pop up stowrz z angular dilog: https://material.angular.io/components/dialog/overview

2023-04-27 19:40 UTC, aleksanderkus00 commented
Na koncu zrob `npm run lint`. Jesli bedzie blad z uruchomieniem daj tu tylko unix.
<img width="410" alt="image" src="https://user-images.githubusercontent.com/91941766/234973547-1c0b99d1-6c11-4b71-a3bb-c3cab8bf2ea9.png">

2023-04-29 08:22 UTC, matuszykrafa requested changes

2023-04-29 08:22 UTC, matuszykrafa commented on .vscode/settings.json
> +{
ten plik nie jest potrzebny. mozna dodac do .gitignore i usunac

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/angular.json
> +    "analytics": false
jest jakis powod tej zmiany?
Prawodopodobnie nie powinno to być tu dodane

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/app/components/popup/popup.component.html
> +    <div class="close-button" (click)="closePopup()" ><img src="assets/svg/x-symbol.svg"/></div>
nie ma potrzeby do uzywania .svg dla ikony typu "X"
Wystarczy uzyc dostepnych w angularz np. "<mat-icon>close</mat-icon>"
Pełna lista dostepnych ikon tutaj: https://www.angularjswiki.com/angular/angular-material-icons-list-mat-icon-list/

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/app/shared/ui/dropdown-select/dropdown-select.component.css
jesli zrobiles osobna css class do selectow (mat-selectow), to prawdopodobnie ten plik mozna usunac

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/app/shared/ui/dropdown-select/dropdown-select.component.html
jesli zrobiles osobna css class do selectow (mat-selectow), to prawdopodobnie ten plik mozna usunac

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/app/shared/ui/dropdown-select/dropdown-select.component.ts
jesli zrobiles osobna css class do selectow (mat-selectow), to prawdopodobnie ten plik mozna usunac

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/app/components/popup/popup.component.ts
przeniosłem ten plik do shared/ui/popup
Prawdopodobnie przy pullowaniu zmian stworzył ci się ponownie.
Powinien się on znajdować w jednym miejscu (w katalogu shared), więc trzeba go stad usunac

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/app/components/popup/popup.component.html
przeniosłem ten plik do shared/ui/popup
Prawdopodobnie przy pullowaniu zmian stworzył ci się ponownie.
Powinien się on znajdować w jednym miejscu (w katalogu shared), więc trzeba go stad usunac

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/app/components/popup/popup.component.css
przeniosłem ten plik do shared/ui/popup
Prawdopodobnie przy pullowaniu zmian stworzył ci się ponownie.
Powinien się on znajdować w jednym miejscu (w katalogu shared), więc trzeba go stad usunac

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/assets/svg/x-symbol.svg
nie ma potrzeby do uzywania .svg dla ikony typu "X".
Wystarczy uzyc dostepnych w angularze np. "<mat-icon>close</mat-icon>". Ten plik mozna usunac
Pełna lista dostepnych ikon tutaj: https://www.angularjswiki.com/angular/angular-material-icons-list-mat-icon-list/

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +html, body { height: 100%; }
style do html, body prawodopodobnie nie powinny byc w tym pliku.
Prawodopodobnie te konkretne style są w ogole nie potrzebne

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    background-color: #f8c48c;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    border-color: #f8c48c;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    background-color: #c2bdb7;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    border-color: #c2bdb7;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    border: solid 2px #3b4a84;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    border: 2px solid #cccccc;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    border-color: #3b4a84;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    color: #3b4a84 ;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    border: 2px solid #3b4a84 !important;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    background-color: #92a7ff !important;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    background-color: #92a7ff !important;
**Jeśli** nie jest to konieczne nie uzywaj "!important"

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    border: 2px solid #3b4a84 !important;
**Jeśli** nie jest to konieczne nie uzywaj "!important"

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/styles/utilities.scss
> +    color: #000000;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/app/shared/ui/popup/popup.component.css
> +    background-color: white;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/app/shared/ui/popup/popup.component.css
> +    background-color: #3B4A84;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-29 08:22 UTC, matuszykrafa commented on frontend/upwork-client/src/app/shared/ui/popup/popup.component.css
> +    color: #fff;
uzyj kolorow z _variables.scss
Jesli nie danego koloru, to dodaj go

2023-04-30 15:29 UTC, merged